name: "DEVKING_CLEANUP"
runs:
  using: "composite"
  steps:
    - shell: bash      
      run: export ACTIONDO=${{ GITHUB.EVENT.INPUTS.ACTIONDO }} ; export FORCE_COLOR=1 ;  export GITHUB_TOKEN=${{ GITHUB.TOKEN }} ; cd ${{ GITHUB.ACTION_PATH }} ; echo "OS = `uname -a`" ; echo "NPM = `npm ci`" ; cd ${{ GITHUB.WORKSPACE }} ; node ${{ GITHUB.ACTION_PATH }}/action.js --loglevel trace